version: "2"

services:
  ez-proxy:
    image: node:12
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/src/app
    working_dir: /src/app
    command: yarn prod-start
    # command: yarn keep-alive
