version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Prepare ez-proxy
          environment:
            CAROOT: .caroot
          command: |
            sudo apt-get install libnss3-tools
            git clone git@github.com:elderapo/ez-proxy.git
            cd ./ez-proxy
            ./.bin/mkcert -install
            docker-compose up -d

      - run:
          name: Run tests
          command: |
            docker-compose -f docker-compose.test.yml up -d
            docker-compose -f docker-compose.test.yml exec ez-proxy-test yarn __runTests
