version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Configure Dnsmasq
          command: sudo echo "address=/.loc/127.0.0.1" > /etc/dnsmasq.conf && sudo sh -c ‘systemctl reload dnsmasq’

      - run:
          name: Prepare ez-proxy
          environment:
            CAROOT: .caroot
          command: |
            sudo apt-get install libnss3-tools
            git clone git@github.com:elderapo/ez-proxy.git
            cd ./ez-proxy
            ./.bin/mkcert -install
            docker-compose up -d

      - run:
          name: Run tests
          command: |
            cd tests
            docker-compose up -d
            docker-compose exec ez-proxy-test yarn __runTests
